CREATE DATABASE IF NOT EXIST my_db

USE my_db

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100),
    email VARCHAR(100)

);

INSERT INTO users(nombre, email) VALUES
("JUAN", "JUAN@GMAIL.COM"),
("MARIA", "MARIA@GMAIL.COM");